[2024-12-03T12:15:04.829+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T12:15:04.853+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_understat_data.run_shot_extraction manual__2024-12-03T12:14:56.691971+00:00 [queued]>
[2024-12-03T12:15:04.863+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_understat_data.run_shot_extraction manual__2024-12-03T12:14:56.691971+00:00 [queued]>
[2024-12-03T12:15:04.865+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-03T12:15:04.947+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_shot_extraction> on 2024-12-03 12:14:56.691971+00:00
[2024-12-03T12:15:04.960+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=110) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T12:15:04.963+0000] {standard_task_runner.py:72} INFO - Started process 113 to run task
[2024-12-03T12:15:04.964+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_understat_data', 'run_shot_extraction', 'manual__2024-12-03T12:14:56.691971+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_epl_inc.py', '--cfg-path', '/tmp/tmpxpfy9q1v']
[2024-12-03T12:15:04.966+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask run_shot_extraction
[2024-12-03T12:15:05.308+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_understat_data.run_shot_extraction manual__2024-12-03T12:14:56.691971+00:00 [running]> on host 84cd6dce77c7
[2024-12-03T12:15:05.485+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='user' AIRFLOW_CTX_DAG_ID='extract_understat_data' AIRFLOW_CTX_TASK_ID='run_shot_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T12:14:56.691971+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T12:14:56.691971+00:00'
[2024-12-03T12:15:05.486+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T12:15:05.487+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T12:15:05.487+0000] {logging_mixin.py:190} INFO - Current task name:run_shot_extraction state:running start_date:2024-12-03 12:15:04.854618+00:00
[2024-12-03T12:15:05.488+0000] {logging_mixin.py:190} INFO - Dag name:extract_understat_data and current dag run status:running
[2024-12-03T12:15:05.488+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T12:15:05.490+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_data_epl_inc.py", line 28, in extract_and_save_shots
    import understatapi
ModuleNotFoundError: No module named 'understatapi'
[2024-12-03T12:15:05.505+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-03T12:15:05.506+0000] {logging_mixin.py:190} INFO - Task start:2024-12-03 12:15:04.854618+00:00 end:2024-12-03 12:15:05.504991+00:00 duration:0.650373
[2024-12-03T12:15:05.506+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): run_shot_extraction> dag:<DAG: extract_understat_data> dagrun:<DagRun extract_understat_data @ 2024-12-03 12:14:56.691971+00:00: manual__2024-12-03T12:14:56.691971+00:00, state:running, queued_at: 2024-12-03 12:14:56.760732+00:00. externally triggered: True>
[2024-12-03T12:15:05.507+0000] {logging_mixin.py:190} INFO - Failure caused by No module named 'understatapi'
[2024-12-03T12:15:05.507+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=extract_understat_data, task_id=run_shot_extraction, run_id=manual__2024-12-03T12:14:56.691971+00:00, execution_date=20241203T121456, start_date=20241203T121504, end_date=20241203T121505
[2024-12-03T12:15:05.584+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T12:15:05.585+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task run_shot_extraction (No module named 'understatapi'; 113)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_data_epl_inc.py", line 28, in extract_and_save_shots
    import understatapi
ModuleNotFoundError: No module named 'understatapi'
[2024-12-03T12:15:05.634+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-03T12:15:05.662+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T12:15:05.748+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
